plugins {
    id 'net.neoforged.moddev' version "${neoforge_moddev_version}"
}

base {
    archivesName = "${project.archives_base_name}-neoforge"
}

neoForge {
    version = project.neoforge_version
    mods {
        firesprinkler {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation project(':common')
}

processResources {
    def props = [
        version: project.version,
        mod_id: project.mod_id,
        mod_name: project.mod_name,
        minecraft_version_min: project.minecraft_version_min,
        neoforge_version_min: project.neoforge_version_min
    ]
    inputs.properties props
    filesMatching("META-INF/neoforge.mods.toml") { expand props }
}

jar {
    from(project(':common').sourceSets.main.output)
    def baseName = base.archivesName.get()
    from("../LICENSE.txt") { rename { "${it}_${baseName}" } }
}
